trash: handle symlinks

diff --git a/bin/trash b/bin/trash
--- a/bin/trash
+++ b/bin/trash
@@ -30,8 +30,14 @@ get_size() {
 dumpster() {
     # trim leading slash, if exists
     file="${1%/}"
-
-    if [ -e "$file" ]; then
+    if [ -L "$file" ] ; then
+        printf 'Found symlink: "%s"  "%s"\n' "$file" "$(readlink "$file")"
+        if unlink "$file" ; then
+            printf 'Unlinked: %s\n' "$file"
+        else
+            >&2 printf 'Failed to unlink: "%s"' "$file"
+        fi
+    elif [ -e "$file" ] ; then
         size="$(get_size "$file")"
         if [ ! "$size" -gt "$MAX_TRASH_SIZE" ] ; then
             mv -vf "$file" "$TRASH_LOCATION/$file-$(rgen).trashed"
