re-add hosts, move custom lists options to files via $HOSTS_CUSTOM_ALLOW / $HOSTS_CUSTOM_BLOCK

diff --git a/rice/gnomebar b/rice/gnomebar
--- a/rice/gnomebar
+++ b/rice/gnomebar
@@ -2,15 +2,20 @@
 #
 # http://github.com/mitchweaver
 #
-# bar I use with gnome, using exector extension
+# bar I use with gnome, using executor extension
 #
+
+SEP='   '
 
 get_traffic() {
     int=wlp0s20f3
-
-    printf ' %s    %s' \
-        "$(human </sys/class/net/$int/statistics/rx_bytes)" \
-        "$(human </sys/class/net/$int/statistics/tx_bytes)"
+    if [ -e /sys/class/net/$int/statistics/rx_bytes ] ; then
+        printf ' %s    %s' \
+            "$(human </sys/class/net/$int/statistics/rx_bytes)" \
+            "$(human </sys/class/net/$int/statistics/tx_bytes)"
+    else
+        >&2 echo "ERROR: $int not found"
+    fi
 }
 
 # Get memory information by parsing /proc/meminfo.
@@ -34,6 +39,7 @@ get_mem() {
     printf ' %s' "$(printf '%s\n' "$((used * 1024))"  | human)"
 }
 
-printf '%s    %s\n' \
+# "$(song)" \
+printf "%s$SEP%s\n" \
     "$(get_mem)" \
     "$(get_traffic)"
