improve piavpn, add daemonized location changer

diff --git a/wrapper/piavpn b/wrapper/piavpn
--- a/wrapper/piavpn
+++ b/wrapper/piavpn
@@ -2,10 +2,11 @@
 #
 # http://github.com/mitchweaver/bin
 #
-# run openvpn as a chrooted user with my settings
+# location rotating openvpn daemon with chrooted
+# nonpriv user with my settings
 #
 # shelcheck bugs:
-# shellcheck disable=2120,SC2119
+# shellcheck disable=2120,SC2119,SC2035,SC1102,SC2034
 #
 
 # -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
@@ -14,6 +15,7 @@
 : "${OVPN_DIR:=/etc/openvpn}"
 : "${LOGIN:=$OVPN_DIR/pia_login}"
 : "${CERT:=$OVPN_DIR/ca.rsa.4096.crt}"
+: "${MINUTES:=5}"
 LOG=/var/log/openvpn.log
 CHROOT_USER=_openvpn
 CHROOT_DIR=/var/openvpn
@@ -24,12 +26,31 @@ elif [ -d /var/run ] ; then
 fi
 # -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
 
+log() { printf '[*] %s\n' "$*" >>"/var/log/${0##*/}.log" ; }
 die() { >&2 printf '%s\n' "$*" ; exit 1 ; }
-usage() { die "Usage: ${0##*/} [-i] [-c] [-q] [-r]" ; }
+
+usage() {
+>&2 cat <<EOF
+Usage: ${0##*/} [options]
+
+Options:
+--------------------
+[-d]    start the daemon
+[-i]    check is running
+[-c]    print current location
+[-l]    view daemon log
+[-r]    restart openvpn
+[-q]    quit
+EOF
+exit 1
+}
 
 init() {
     # re-run scipt as root if we are not already
-    [ "$(id -u)" -eq 0 ] || exec sudo "$0" "$@"
+    if [ "$(id -u)" -ne 0 ] ;then
+        sudo "$0" "$@"
+        exit $?
+    fi
 
     # create the restricted user/group if they doesn't exist
     id $CHROOT_USER >/dev/null 2>&1 || \
@@ -91,7 +112,7 @@ run() {
     PORT=1197
     DOMAIN=privateinternetaccess.com
     REMOTE=$LOC.$DOMAIN
-    $(command -v openvpn) \
+    exec "$(command -v openvpn)" \
         --remote "$REMOTE" "$PORT" \
         --auth-user-pass "$LOGIN" \
         --ca $CERT \
@@ -141,22 +162,81 @@ current() {
 stop_vpn() {
     isrunning || die "Not running."
     read -r pid <$PIDFILE
-    sudo kill -9 "$pid"
-    sudo rm $PIDFILE
+    kill -9 "$pid"
+    rm $PIDFILE
 }
 
 start_vpn() {
     isrunning && die "Already running."
     init
     get_loc
-    run
+    run &
+    log "started openvpn on pid $! using location: $LOC"
 }
 
-case $1 in
-    -h) usage ;;
-    -i) isrunning ;;
-    -c) current ;;
-    -q) stop_vpn ;;
-    -r) stop_vpn ; start_vpn ;;
-     *) start_vpn
+start_daemon() {
+    init "$@"
+
+    echo $$ > "/var/cache/${0##*/}.pid"
+
+    :>"/var/log/${0##*/}.log"
+    chmod 600 "/var/log/${0##*/}.log"
+
+    while : ; do
+        log 'changing locs'
+        start_vpn &
+
+        # -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
+        # fix later
+        shift_amount=$(LC_ALL=C \
+        tr -dc 0-9 < /dev/urandom | \
+        dd ibs=1 obs=1 count=2 2>/dev/null)
+
+        if [ "$(LC_ALL=C tr -dc 0-9 < /dev/urandom | \
+            dd ibs=1 obs=1 count=1 2>/dev/null)" -eq 1 ] ; then
+            amount="$(( MINUTES * 60 - shift_amount))"
+        else
+            amount="$(( MINUTES * 60 + shift_amount))"
+        fi
+        log "sleeping for $amount seconds"
+        sleep "$amount"
+        # -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
+        
+        stop_vpn
+    done >>"/var/log/${0##*/}.log" 2>&1 &
+}
+
+stop_daemon() {
+    if [ -f "/var/cache/${0##*/}.pid" ] ; then
+        read -r pid < "/var/cache/${0##*/}.pid"
+    else
+        die "Daemon not running or pid could not be found."
+    fi
+    kill -9 "$pid"
+    rm "$pid"
+    stop_vpn
+}
+
+case ${1#-} in
+    h|'')
+        usage
+        ;;
+    i)
+        isrunning
+        ;;
+    c)
+        current
+        ;;
+    l)
+        sudo tail -f "/var/log/${0##*/}.log"
+        ;;
+    *)
+        init "$@"
+
+        case ${1#-} in
+            d) start_daemon "$@" ;;
+            q) stop_daemon ;;
+            r) stop_vpn ; start_vpn ;;
+            *) usage
+        esac
 esac
