bar: improve skroll
fixup

diff --git a/wrapper/pkg b/wrapper/pkg
--- a/wrapper/pkg
+++ b/wrapper/pkg
@@ -30,12 +30,15 @@ case $flag in
     s|-s)
         pkg_info -Q "$@"
         ;;
+    ps|ps)
+        make -f /usr/ports/Makefile search key="$1"
+        ;;
     pi|-pi)
         port=$(findport "$1")
         if [ "$port" ] ; then
             cat $port/pkg/DESCR
         else
-            >&2 "port $1 not found"
+            >&2 echo "port ${1##*/} not found"
             exit 1
         fi
         ;;
